apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlp-cooker-training-job
  namespace: argo
  annotations:
    description: "通过MLP Cooker后端API创建训练任务"
spec:
  entrypoint: create-training-job
  
  # 参数定义
  arguments:
    parameters:
      # MLP Cooker后端API地址
      - name: mlp-cooker-api
        description: "MLP Cooker后端API地址"
        value: "http://mlp-cooker-backend:5002"
      
      # 训练任务参数（JSON格式）
      - name: task-params
        description: "训练任务参数（JSON格式）"
        value: |
          {
            "name": "pytorch-training-job",
            "jobType": "PyTorchJob",
            "command": "python train.py",
            "jobSpec": {
              "replicas": 1,
              "image": "registry.baidubce.com/aihc-aiak/pytorch:latest",
              "resources": [],
              "envs": [
                {
                  "name": "NCCL_DEBUG",
                  "value": "INFO"
                }
              ],
              "enableRDMA": true
            },
            "datasources": [
              {
                "type": "pfs",
                "mountPath": "/data"
              }
            ]
          }
  
  # 模板定义
  templates:
    # 主模板：创建训练任务
    - name: create-training-job
      container:
        image: curlimages/curl:latest
        command: [sh, -c]
        args:
          - |
            set -e
            
            echo "=========================================="
            echo "创建训练任务"
            echo "=========================================="
            echo "API地址: {{workflow.parameters.mlp-cooker-api}}"
            echo ""
            
            # 调用MLP Cooker后端API创建训练任务
            RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
              "{{workflow.parameters.mlp-cooker-api}}/api/jobs/create" \
              -H "Content-Type: application/json" \
              -d "{\"taskParams\": {{workflow.parameters.task-params}}}")
            
            # 分离HTTP状态码和响应体
            HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
            BODY=$(echo "$RESPONSE" | sed '$d')
            
            echo "HTTP状态码: $HTTP_CODE"
            echo "响应内容: $BODY"
            echo ""
            
            # 检查HTTP状态码
            if [ "$HTTP_CODE" != "200" ]; then
              echo "❌ 请求失败，HTTP状态码: $HTTP_CODE"
              exit 1
            fi
            
            # 解析响应
            SUCCESS=$(echo "$BODY" | grep -o '"success":[^,}]*' | grep -o '[^:]*$' | tr -d ' ')
            
            if [ "$SUCCESS" = "true" ]; then
              echo "✅ 训练任务创建成功！"
              echo "$BODY" > /tmp/response.json
              exit 0
            else
              echo "❌ 训练任务创建失败"
              echo "$BODY"
              exit 1
            fi
      
      # 输出结果
      outputs:
        parameters:
          - name: response
            valueFrom:
              path: /tmp/response.json

